[package]
name = "podboy"
version = "0.1.3"
edition = "2021"
description = "A daemon system for podman"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }

