[package]
name = "podboy"
version = "0.1.4"
edition = "2021"
description = "Pods with Borderless orchestration (yes)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

